export const ERROR_CODE = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  SEAT_UNAVAILABLE: "SEAT_UNAVAILABLE",
  HOLD_NOT_FOUND: "HOLD_NOT_FOUND",
  HOLD_EXPIRED: "HOLD_EXPIRED",
  HOLD_ALREADY_CONFIRMED: "HOLD_ALREADY_CONFIRMED",
  SCREENING_NOT_FOUND: "SCREENING_NOT_FOUND",
  ERROR: "ERROR",
  INTERNAL: "INTERNAL",
  UNKNOWN: "UNKNOWN",
} as const;
