export const RULE_ERROR_CODE = {
  EMPTY_SELECTION: "EMPTY_SELECTION",
  OUT_OF_RANGE: "OUT_OF_RANGE",
  DUPLICATE_SEAT: "DUPLICATE_SEAT",
  SEAT_UNAVAILABLE: "SEAT_UNAVAILABLE",
  NOT_CONSECUTIVE: "NOT_CONSECUTIVE",
  ISOLATED_SEAT: "ISOLATED_SEAT",
} as const;
